[2024-06-14 19:04:27,922] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_ml_to_postgres.upload_to_s3 manual__2024-06-14T19:03:54.684622+00:00 [queued]>
[2024-06-14 19:04:27,926] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_ml_to_postgres.upload_to_s3 manual__2024-06-14T19:03:54.684622+00:00 [queued]>
[2024-06-14 19:04:27,926] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-06-14 19:04:27,926] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-06-14 19:04:27,926] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-06-14 19:04:27,932] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-06-14 19:03:54.684622+00:00
[2024-06-14 19:04:27,934] {standard_task_runner.py:52} INFO - Started process 28820 to run task
[2024-06-14 19:04:27,936] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 's3_to_ml_to_postgres', 'upload_to_s3', 'manual__2024-06-14T19:03:54.684622+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/ml_dataset_preparation.py', '--cfg-path', '/tmp/tmp0_s_ybwn', '--error-file', '/tmp/tmpev3hg658']
[2024-06-14 19:04:27,936] {standard_task_runner.py:80} INFO - Job 37: Subtask upload_to_s3
[2024-06-14 19:04:27,956] {task_command.py:370} INFO - Running <TaskInstance: s3_to_ml_to_postgres.upload_to_s3 manual__2024-06-14T19:03:54.684622+00:00 [running]> on host 92769061d4a4
[2024-06-14 19:04:27,982] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_to_ml_to_postgres
AIRFLOW_CTX_TASK_ID=upload_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-06-14T19:03:54.684622+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-14T19:03:54.684622+00:00
[2024-06-14 19:04:27,985] {base.py:68} INFO - Using connection ID 'aws_default' for task execution.
[2024-06-14 19:04:27,986] {base_aws.py:206} INFO - Credentials retrieved from login
[2024-06-14 19:04:27,986] {base_aws.py:100} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2024-06-14 19:04:28,935] {python.py:173} INFO - Done. Returned value was: None
[2024-06-14 19:04:28,946] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_to_ml_to_postgres, task_id=upload_to_s3, execution_date=20240614T190354, start_date=20240614T190427, end_date=20240614T190428
[2024-06-14 19:04:28,975] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-06-14 19:04:28,992] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
