[2024-06-16T19:51:30.982+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_ml_to_postgres.s3_to_redshift manual__2024-06-16T19:48:57.135352+00:00 [queued]>
[2024-06-16T19:51:30.985+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_ml_to_postgres.s3_to_redshift manual__2024-06-16T19:48:57.135352+00:00 [queued]>
[2024-06-16T19:51:30.986+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-06-16T19:51:30.990+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): s3_to_redshift> on 2024-06-16 19:48:57.135352+00:00
[2024-06-16T19:51:30.992+0000] {standard_task_runner.py:60} INFO - Started process 34786 to run task
[2024-06-16T19:51:30.994+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 's3_to_ml_to_postgres', 's3_to_redshift', 'manual__2024-06-16T19:48:57.135352+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/ml_dataset_preparation.py', '--cfg-path', '/tmp/tmp0kioc2gx']
[2024-06-16T19:51:30.996+0000] {standard_task_runner.py:88} INFO - Job 187: Subtask s3_to_redshift
[2024-06-16T19:51:31.014+0000] {task_command.py:423} INFO - Running <TaskInstance: s3_to_ml_to_postgres.s3_to_redshift manual__2024-06-16T19:48:57.135352+00:00 [running]> on host 22dc78ccc862
[2024-06-16T19:51:31.040+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_ml_to_postgres' AIRFLOW_CTX_TASK_ID='s3_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T19:48:57.135352+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T19:48:57.135352+00:00'
[2024-06-16T19:51:31.044+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2024-06-16T19:51:31.046+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2024-06-16T19:51:31.046+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-06-16T19:51:31.051+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2024-06-16T19:51:31.053+0000] {base.py:83} INFO - Using connection ID 'redshift_conn_id' for task execution.
[2024-06-16T19:51:31.777+0000] {sql.py:450} INFO - Running statement: 
                    COPY PUBLIC.transformed_data 
                    FROM 's3://velib-project/transformed_data.csv'
                    credentials
                    'aws_access_key_id=AKIA47CRVUXOGVJZJMVK;aws_secret_access_key=***'
                    
                    csv
			IGNOREHEADER 1
			MAXERROR 1000
			DELIMITER ','
			FILLRECORD;
        , parameters: None
[2024-06-16T19:51:45.365+0000] {s3_to_redshift.py:197} INFO - COPY command complete...
[2024-06-16T19:51:45.372+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=s3_to_ml_to_postgres, task_id=s3_to_redshift, execution_date=20240616T194857, start_date=20240616T195130, end_date=20240616T195145
[2024-06-16T19:51:45.393+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-06-16T19:51:45.401+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
